### ISSUE TITLE
Some suggestions  

### ISSUE THREAD

**Issue by TalzoorBgu** [SensorsIot/ESP32-OTA#11]
Hello Andreas,
Appreciate your work a LOT! Thank you for all the good tips.

Some suggestions that I think needed in this code:

`#define ESP32_RTOS` should come before `#include "OTA.h"`
otherwise it's not activating what its suppose to.

inside OTA.h file:
`void taskOne`... should be `void ota_handle`... as it referred later.
and I am new to freeRTOS as well but learned that tasks cannot just end without `vTaskDelete` statement.  otherwise an error pops out.
Here, you don't wont the task to end so it acutely need to be in its own loop, something like:
`#if defined(ESP32_RTOS) && defined(ESP32)`
`void ota_handle( void * parameter )`
`{`
`while (1) {`
`    ArduinoOTA.handle();`
`    delay(3500);`
`  } //end while`
`}`
`#endif`

**Comment by 2010019970909** [comment]
Hello @TalzoorBgu,

I did the PR #10 in that way.

Have a nice day,
Vincent

**Comment by Wistrel** [comment]
Ah sorry I'm a bit new to github. Looks like I've recently fixed these up without realising others were on the same problem. I think it's been checked now and awaiting merge.

**Comment by 2010019970909** [comment]
@Wistrel, don't worry, I'm new too 😄 . I'll try to reach Andreas in the comment of my PR, I've added some comments to your PR. If mine gets merged, you can close yours if you agree. Again thanks for your work.

**Comment by SensorsIot** [comment]
A pull request should have solved the problem.
