### ISSUE TITLE
"invalid use of 'void'"

### ISSUE THREAD

**Issue by Stargate67** [SensorsIot/ESP32-OTA#6]
Hi Andreas, 
I tried to use this library on my sketches with first testing the included one like "0TA_Template_Sketch_TelnetStream" on an  "generic 8266" board. But got "invalid use of 'void'"
on line 59 ".onEnd([]() {" in OTA.h  library. 
This, on 2 different laptops with Arduino IDE 1.8.12.
I am not able to find from where this can happen...
Thanks in advance for your help.
Yves 

![2020-06-15 21_51_49-0TA_Template_Sketch_TelnetStream - OTA h _ Arduino 1 8 12](https://user-images.githubusercontent.com/66971848/84699854-9201ec00-af52-11ea-9aa8-aba950713c22.png)

**Comment by bramhut** [comment]
Hi,
I was able to fix this by breaking up the chain functions. Replacing the `.onEnd`  and other functions with `ArduinoOTA.onEnd` and using a semicolon after each function call. It seems only to be an issue with an ESP8266: [Link to arduino forum](https://forum.arduino.cc/index.php?topic=623322.0)
I have created a pull request for this solution
Hope this helps!

**Comment by SensorsIot** [comment]
A pull request should have solved the problem.
